{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stas-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "stas.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuer | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.webHost }}
        - {{ .Values.ingress.apiHost }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.webHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stas-web
                port:
                  number: {{ .Values.web.service.port }}
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stas-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
